sudo: false
language: python
python:
- '2.7'
- pypy
install:
- pip install tox coveralls
script:
- tox -r
after_success:
- coverage report
- coveralls
notifications:
    email:
        recipients:
            - josuebrunel@gmail.com
        on_success: change
        on_failure: always
