sudo: false
language: python
matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env:  TOXENV=py36
install:
- pip install tox coveralls
script:
- tox -r
after_success:
- coverage report
- coveralls
notifications:
    email:
        recipients:
            - josuebrunel@gmail.com
        on_success: change
        on_failure: always
